const fs=require('fs'),path=require('path');
const dir=__dirname;
const cfg={larguraMm:3,diametroInternoMm:18,espessuraMm:1.35,segmentos:384,perfil:96};
const pos=[],norm=[],ids=[[],[]]; const N=cfg.segmentos,M=cfg.perfil;
// Closed elliptical anatomical section, swept around the ring axis (Z).
for(let i=0;i<=N;i++){let a=i/N*Math.PI*2; for(let j=0;j<=M;j++){let t=j/M*2*Math.PI,r=9+.675+.675*Math.cos(t),z=1.5*Math.sin(t);pos.push(r*Math.cos(a)/1000,r*Math.sin(a)/1000,z/1000);let nr=Math.cos(t)/.675,nz=Math.sin(t)/1.5,l=Math.hypot(nr,nz);norm.push(nr*Math.cos(a)/l,nr*Math.sin(a)/l,nz/l);}}
for(let i=0;i<N;i++)for(let j=0;j<M;j++){let a=i*(M+1)+j,b=a+M+1;let material=Math.cos((j+.5)/M*2*Math.PI)>=0?0:1;ids[material].push(a,b,a+1,b,b+1,a+1);}
function glb(pair){let chunks=[],views=[],accessors=[],offset=0;function add(arr,type,componentType,min,max){let b=Buffer.from(arr.buffer);views.push({buffer:0,byteOffset:offset,byteLength:b.length});chunks.push(b);offset+=b.length;accessors.push({bufferView:views.length-1,componentType,count:arr.length/(type==='VEC3'?3:1),type,...(min?{min,max}:{})});return accessors.length-1;}
let p=add(new Float32Array(pos),'VEC3',5126,[-.01035,-.01035,-.0015],[.01035,.01035,.0015]),n=add(new Float32Array(norm),'VEC3',5126);let primitives=ids.map((v,m)=>({attributes:{POSITION:p,NORMAL:n},indices:add(new Uint32Array(v),'SCALAR',5125),material:m}));let nodes=pair?[{mesh:0,name:'03LM principal',translation:[.005,0,0]},{mesh:0,name:'03LM secundária',scale:[.89,.89,1],translation:[-.015,-.003,.005]}]:[{mesh:0,name:'03LM 3mm'}];
let doc={asset:{version:'2.0',generator:'03LM parametric reconstruction'},scene:0,scenes:[{nodes:nodes.map((_,i)=>i)}],nodes,meshes:[{primitives}],materials:[{name:'Exterior dourado polido',pbrMetallicRoughness:{baseColorFactor:[.95,.64,.22,1],metallicFactor:1,roughnessFactor:.10}},{name:'Interior prateado polido (referência visual)',pbrMetallicRoughness:{baseColorFactor:[.72,.75,.78,1],metallicFactor:1,roughnessFactor:.12}}],buffers:[{byteLength:offset}],bufferViews:views,accessors,extras:{...cfg,observacao:'Largura confirmada pelo catálogo. Diâmetro e espessura estimados. Materiais reproduzem a aparência da foto, sem certificar composição.'}};let js=Buffer.from(JSON.stringify(doc));js=Buffer.concat([js,Buffer.alloc((4-js.length%4)%4,32)]);let bin=Buffer.concat(chunks),h=Buffer.alloc(20),bh=Buffer.alloc(8);h.writeUInt32LE(0x46546c67,0);h.writeUInt32LE(2,4);h.writeUInt32LE(28+js.length+bin.length,8);h.writeUInt32LE(js.length,12);h.writeUInt32LE(0x4e4f534a,16);bh.writeUInt32LE(bin.length,0);bh.writeUInt32LE(0x004e4942,4);return Buffer.concat([h,js,bh,bin]);}
fs.writeFileSync(path.join(dir,'03LM.glb'),glb(false));fs.writeFileSync(path.join(dir,'03LM-par.glb'),glb(true));
let indices=ids.flat(),stl=Buffer.alloc(84+indices.length/3*50);stl.write('03LM - mm - estimated diameter and thickness');stl.writeUInt32LE(indices.length/3,80);for(let k=0;k<indices.length;k+=3){let at=84+k/3*50;let v=indices.slice(k,k+3).map(i=>pos.slice(i*3,i*3+3).map(x=>x*1000));let u=v[1].map((x,i)=>x-v[0][i]),w=v[2].map((x,i)=>x-v[0][i]);let n=[u[1]*w[2]-u[2]*w[1],u[2]*w[0]-u[0]*w[2],u[0]*w[1]-u[1]*w[0]],l=Math.hypot(...n);[...n.map(x=>x/l),...v.flat()].forEach((x,i)=>stl.writeFloatLE(x,at+4*i));}fs.writeFileSync(path.join(dir,'03LM.stl'),stl);
fs.writeFileSync(path.join(dir,'modelo.js'),'export const modelo="data:model/gltf-binary;base64,'+glb(false).toString('base64')+'";');
console.log(JSON.stringify({vertices:pos.length/3,triangulos:indices.length/3,arquivos:['03LM.glb','03LM-par.glb','03LM.stl']}));
